version: "3.7"
services:
  node:
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "${LOCAL_NODE_PORT}:${NODE_CONTAINER_PORT}"
    volumes:
      - ${LOCAL_PATH_APP}:${NODE_PATH_APP}
    networks:
      - frontend
networks:
  frontend: